import { createReducer , on} from "@ngrx/store";
import { ItemList } from "../../utils/Item.model";
import {add, clear, remove, increase, decrease} from "./shopping.actions";

const initialState={
    shopItemList:[
    new ItemList("headphones", "Fastrack Fpods(New Launch) FZ100 TWS in-Ear Earbuds with Mega 50 Hrs Playtime|Extra Deep Bass Driver|Quad Mic ENC for Clear Calls|Ultra Low 40ms Latency Gaming Mode|NitroFast Charge-200 Min in 10 Min","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4GnI_aR4lo1c1o1rlX4AjoZCTVIojl-pLKw&s", 999,1, ["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("Alexa Speaker","Amazon Echo Dot (5th Gen) | Smart speaker with Bigger sound, Motion Detection, Temperature Sensor, Alexa and Bluetooth| Blue", "https://m.media-amazon.com/images/I/81WaomQESKL._AC_UY436_FMwebp_QL65_.jpg",5499,1, ["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("headphones", "Fastrack Fpods(New Launch) FZ100 TWS in-Ear Earbuds with Mega 50 Hrs Playtime|Extra Deep Bass Driver|Quad Mic ENC for Clear Calls|Ultra Low 40ms Latency Gaming Mode|NitroFast Charge-200 Min in 10 Min", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4GnI_aR4lo1c1o1rlX4AjoZCTVIojl-pLKw&s",999,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("Alexa Speaker","Amazon Echo Dot (5th Gen) | Smart speaker with Bigger sound, Motion Detection, Temperature Sensor, Alexa and Bluetooth| Blue", "https://m.media-amazon.com/images/I/81WaomQESKL._AC_UY436_FMwebp_QL65_.jpg",5499,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("headphones", "Fastrack Fpods(New Launch) FZ100 TWS in-Ear Earbuds with Mega 50 Hrs Playtime|Extra Deep Bass Driver|Quad Mic ENC for Clear Calls|Ultra Low 40ms Latency Gaming Mode|NitroFast Charge-200 Min in 10 Min","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4GnI_aR4lo1c1o1rlX4AjoZCTVIojl-pLKw&s", 999,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("Alexa Speaker","Amazon Echo Dot (5th Gen) | Smart speaker with Bigger sound, Motion Detection, Temperature Sensor, Alexa and Bluetooth| Blue","https://m.media-amazon.com/images/I/81WaomQESKL._AC_UY436_FMwebp_QL65_.jpg", 5499,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("headphones", "Fastrack Fpods(New Launch) FZ100 TWS in-Ear Earbuds with Mega 50 Hrs Playtime|Extra Deep Bass Driver|Quad Mic ENC for Clear Calls|Ultra Low 40ms Latency Gaming Mode|NitroFast Charge-200 Min in 10 Min","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4GnI_aR4lo1c1o1rlX4AjoZCTVIojl-pLKw&s", 999,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("Alexa Speaker","Amazon Echo Dot (5th Gen) | Smart speaker with Bigger sound, Motion Detection, Temperature Sensor, Alexa and Bluetooth| Blue", "https://m.media-amazon.com/images/I/81WaomQESKL._AC_UY436_FMwebp_QL65_.jpg",5499,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("headphones", "Fastrack Fpods(New Launch) FZ100 TWS in-Ear Earbuds with Mega 50 Hrs Playtime|Extra Deep Bass Driver|Quad Mic ENC for Clear Calls|Ultra Low 40ms Latency Gaming Mode|NitroFast Charge-200 Min in 10 Min", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4GnI_aR4lo1c1o1rlX4AjoZCTVIojl-pLKw&s",999,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("Alexa Speaker","Amazon Echo Dot (5th Gen) | Smart speaker with Bigger sound, Motion Detection, Temperature Sensor, Alexa and Bluetooth| Blue", "https://m.media-amazon.com/images/I/81WaomQESKL._AC_UY436_FMwebp_QL65_.jpg",5499,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("headphones", "Fastrack Fpods(New Launch) FZ100 TWS in-Ear Earbuds with Mega 50 Hrs Playtime|Extra Deep Bass Driver|Quad Mic ENC for Clear Calls|Ultra Low 40ms Latency Gaming Mode|NitroFast Charge-200 Min in 10 Min","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4GnI_aR4lo1c1o1rlX4AjoZCTVIojl-pLKw&s", 999,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("Alexa Speaker","Amazon Echo Dot (5th Gen) | Smart speaker with Bigger sound, Motion Detection, Temperature Sensor, Alexa and Bluetooth| Blue","https://m.media-amazon.com/images/I/81WaomQESKL._AC_UY436_FMwebp_QL65_.jpg", 5499,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("headphones", "Fastrack Fpods(New Launch) FZ100 TWS in-Ear Earbuds with Mega 50 Hrs Playtime|Extra Deep Bass Driver|Quad Mic ENC for Clear Calls|Ultra Low 40ms Latency Gaming Mode|NitroFast Charge-200 Min in 10 Min","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4GnI_aR4lo1c1o1rlX4AjoZCTVIojl-pLKw&s", 999,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("Alexa Speaker","Amazon Echo Dot (5th Gen) | Smart speaker with Bigger sound, Motion Detection, Temperature Sensor, Alexa and Bluetooth| Blue","https://m.media-amazon.com/images/I/81WaomQESKL._AC_UY436_FMwebp_QL65_.jpg", 5499,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("headphones", "Fastrack Fpods(New Launch) FZ100 TWS in-Ear Earbuds with Mega 50 Hrs Playtime|Extra Deep Bass Driver|Quad Mic ENC for Clear Calls|Ultra Low 40ms Latency Gaming Mode|NitroFast Charge-200 Min in 10 Min","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4GnI_aR4lo1c1o1rlX4AjoZCTVIojl-pLKw&s", 999,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
    new ItemList("Alexa Speaker","Amazon Echo Dot (5th Gen) | Smart speaker with Bigger sound, Motion Detection, Temperature Sensor, Alexa and Bluetooth| Blue", "https://m.media-amazon.com/images/I/81WaomQESKL._AC_UY436_FMwebp_QL65_.jpg",5499,1,["Quick charge technology: Get 5 hours of premium stereo sound with just a 10-minute charge, with an unrivalled 50-hour total battery playtime; perfect for the time-conscious music lover","Immersive HD stereo sound: Engineered with precision, a built-in 5 Band EQ, customizable sound modes for a personalized listening experience, and adaptive hybrid ANC for noise-free audio", "All-day comfort: A lightweight and ergonomic design with soft, cushioned ear cups and an adjustable headband for extended listening sessions","Full control at your fingertips: Navigate through your music and manage phone calls by simply tapping to play or pause, sliding to adjust volume, and swiping to change tracks or answer/end calls"]),
  ],
  cartList:[
    
  ],
}
export const shoppingReducer=createReducer(
    initialState,
    on(add, (state, action)=>({
        ...state,
        cartList:[...state.cartList, state.shopItemList[action.value]]
    })),
    on(remove,(state,action)=>(
        {
            ...state,
            cartList: state.cartList.filter((val,index)=>{
                return (index!==action.value);
            })
        }
    )),
    on(clear, (state)=>({
        ...state,
        cartList: []
    })),
    on(increase, (state,action)=>({
        ...state,
        cartList: state.cartList.map((val,index)=>{
            if(index==action.value){
                return {...val, quantity: val.quantity+1};
            }
            return val;
        })
    })),
    on(decrease, (state,action)=>({
        ...state,
        cartList: state.cartList.map((val,index)=>{
            if(action.value==index){
                return {...val, quantity: val.quantity-1};
            }
            return val;
        })
    }))
)